TASK-46944 : fixed displaying wrong week number
exoplatform/analytics pull request #163
Opened 2021-09-13 14:20 UTC by GouadriaHanen

in analytics when choosing  'X AXIS' tab in the top menu and check 'Per week' it displays a wrong week number (actual week number +1)
since the DateTimeFormatter.ofPattern(' 'W' w uuuu') returns  week-based date without an offset
fixed by formatting date with 'BASIC_ISO_DATE' that return the right week number without offset

2021-09-13 16:05 UTC, AzmiTouil requested changes

2021-09-13 16:05 UTC, AzmiTouil commented on analytics-api/src/main/java/org/exoplatform/analytics/model/filter/aggregation/AnalyticsAggregation.java
> +    return dateFormated;
Reformat code please!

2021-09-13 17:39 UTC, AzmiTouil requested changes

2021-09-13 17:39 UTC, AzmiTouil commented on analytics-api/src/main/java/org/exoplatform/analytics/model/filter/aggregation/AnalyticsAggregation.java
> +       dateFormated = date[1]+"-"+date[0];
```suggestion
    String dateFormated = dateTime.format(dateFormatter.withLocale(userLocale));
    if (interval.equals(WEEK_INTERVAL)) {
      String[] date = dateFormated.split("-");
      dateFormated = date[1] + "-" + date[0];
```

2021-09-14 08:29 UTC, GouadriaHanen commented on analytics-api/src/main/java/org/exoplatform/analytics/model/filter/aggregation/AnalyticsAggregation.java
> +       dateFormated = date[1]+"-"+date[0];
done!

2021-09-14 08:32 UTC, AzmiTouil approved these changes
LGTM

2021-09-14 08:33 UTC, merged